language: ruby
sudo: false # taking advantage of container-based infrastructure
cache: bundler # maybe someday they'll add support for us freeloaders...
os:
  - linux
  - osx
rvm:
  - 2.0
  - 2.1
  - 2.2