language: ruby
# sudo: false # taking advantage of container-based infrastructure
# cache: bundler # maybe someday they'll add support for us freeloaders...
# before_install:
#   - rvm install 2.2
#   - brew update
rvm:
  - 2.1
  - 2.2
os: # Does MacOS X work?
  - linux
  - osx
