dist: trusty
language: ruby
sudo: false # taking advantage of container-based infrastructure
cache: bundler # cache bundled gems from build to build
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
matrix:
  allow_failures:
    - rvm: 2.3.0
